-- 002_create_cookies_table_up.sql
CREATE TABLE IF NOT EXISTS COOKIES (
    SessionID TEXT NULL,
    UserID INTEGER,
    CreationDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    ExpirationDate DATETIME,
    FOREIGN KEY (UserID) REFERENCES USERS(Id) ON DELETE SET NULL
);