-- 004_create_comments_table_up.sql
CREATE TABLE IF NOT EXISTS COMMENTS (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
	PostID INTEGER,
	UserID INTEGER,
	Body TEXT,
	CreationDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	ReactionID INTEGER DEFAULT 0,
	FOREIGN KEY (PostID) REFERENCES POSTS(Id) ON DELETE SET NULL,
	FOREIGN KEY (UserID) REFERENCES USERS(Id) ON DELETE SET NULL,
    FOREIGN KEY (ReactionID) REFERENCES COMMENTREACTIONS(Id) ON DELETE SET DEFAULT
);
