-- 004_create_comments_table_up.sql
CREATE TABLE IF NOT EXISTS COMMENTS (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    PostID INTEGER,
	Username TEXT,
	Body TEXT,
	CreationDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	Likes INTEGER,
	Dislikes INTEGER,
	WhoLiked TEXT,
	WhoDisliked TEXT
);
