-- 005_create_POSTREACTIONS_table_up.sql
CREATE TABLE IF NOT EXISTS POSTREACTIONS (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Likes INTEGER DEFAULT 0,
    Dislikes INTEGER DEFAULT 0,
    WhoLiked TEXT DEFAULT '',
    WhoDisliked TEXT DEFAULT ''
);