-- 006_create_CHAT_table_up.sql
CREATE TABLE IF NOT EXISTS CHAT (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  ChatUUID TEXT,
  SenderID INTEGER,
  RecipientID INTEGER,
  Body TEXT,
  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP, 
  FOREIGN KEY (SenderID) REFERENCES USERS(Id) ON DELETE SET NULL,
  FOREIGN KEY (RecipientID) REFERENCES USERS(Id) ON DELETE SET NULL
);